### ISSUE TITLE
Support uploading GB+ files

### ISSUE THREAD

**Issue by MrkGrgsn** [open-data/ckanext-cloudstorage#4]
Hi @TkTech. Thanks for the heads up about this new extension.  In some brief testing I've just done it appears that the limiting factors for large uploads are:
1. Temp disk space. My httpd2.4/mod_wsgi install was writing to `/tmp`
2. Network.server timeouts. CKAN makes a single POST request so I'm guessing it will trip over timeouts in the server (nginx, httpd, etc) or infrastructure (e.g., AWS ELB) once the files get large enough or the upload bandwidth is limited.

Is that a good description of the issues faced to allow files in the order of GBs to be uploaded?

Have you already got plans for implementing multi-part uploads from the browser to CKAN to overcome these problems? We've got a client with up to 100GB files using S3 so we have an opportunity to contribute.

**Comment by TkTech** [comment]
I have not, although it was a problem I noticed from the get-go and one that would be great to solve. Our use case doesn't currently make it a priority for my time.

There are a couple of solutions.

1. When secure urls are configured and available (for S3 and for Azure), they can be created with a `write` flag instead of `read`. This would allow us to generate a temporary URL we can have the client's browser upload to directly on S3/Azure. A bit of [optional] Javascript for a progress bar would be ideal and mean that CKAN never even sees the file being uploaded.
2. In all other instances, CKANs file uploader interface needs a bit of stubbing so that we can get the file in chunks instead of all at once from the tmp folder using the CGI interface. Combined with something like gunicorn should allow a single CKAN instance to handle a few thousand uploads at once.

A big bonus on both of these would be support for resuming uploads. This would also deal with timeouts.

**Comment by MrkGrgsn** [comment]
Good options. I view resuming as a necessity for the filesizes we're going to be dealing with. I'll chat with @smotornyuk and work out what Link can do.

**Comment by MrkGrgsn** [comment]
@smotornyuk has done some good work on this now.  We went with option 2 using the jQuery File Upload widget to allow multi-part uploads via CKAN for any provider (the browser to CKAN part only, of course). 

Downloads are resumable after any type of failure. You can in fact close your browser then re-open CKAN, manage the resource, and resume the upload.  

Sergey, when will you make a PR?

**Comment by TkTech** [comment]
@MrkGrgsn Any update? This is an exciting feature!

**Comment by MrkGrgsn** [comment]
We're already using it in a pre-prod environment, which is not publicly accessible so I can't give you the link unfortunately.  I'll chase Sergey to submit the PR!

**Comment by yanikkoval** [comment]
Hi, guys.

Currently, we are dealing with the same issue. 
Will be glad to test / submit PR. But we will need some hands-on tests first. 

Cheers!

**Comment by Victor1989** [comment]
Hi guys. We'd like to use your extension and I want to know does it support uploading files direct to s3 without loading file to server?

**Comment by MrkGrgsn** [comment]
@TkTech Sergey has promised he'll submit the PR in the next day or two. He mentioned something about more tests.

@Victor1989 no it doesn't. The PR we're discussing provides multi-part upload to S3 (or Azure, etc) but via the CKAN server not direct to the cloud storage. Each part is uploaded to the CKAN Server and from there to the cloud storage. 

The server disk space usage doesn't scale with upload file size but rather with the number of simultaneous uploads. It does however use network bandwidth between the client and CKAN, and then between CKAN and the cloud storage.

**Comment by Victor1989** [comment]
Hi guys. Are there any updates?

**Comment by MrkGrgsn** [comment]
Hi @Victor1989  the work is in the [multipart-uploader branch](https://github.com/smotornyuk/ckanext-cloudstorage/tree/multipart-uploader) of @smotornyuk's fork. I think he is just worried that there isn't sufficient test coverage and hasn't had the time to progress it.

**Comment by Victor1989** [comment]
Hi guys. I tried to use this fork, but got "AttributeError: 'Element' object has no attribute 'nsmap'"

 Module ckanext.cloudstorage.logic.action.multipart:93 in initiate_multipart         view
>>  '{%s}UploadId' % resp.object.nsmap[None]).text
AttributeError: 'Element' object has no attribute 'nsmap'

**Comment by smotornyuk** [comment]
I added handler for this error and made PR

**Comment by MrkGrgsn** [comment]
Closed by #6

**Comment by wild276** [comment]
Hi @TkTech 

Did you explore option 1 (https://github.com/TkTech/ckanext-cloudstorage/issues/4#issuecomment-231766166) in any detail?
We're building on AWS and our clients are wanting to upload files of 200GB+. I saw the current solution has been tested to around 50GB (https://github.com/ckan/ckan/issues/4011#issuecomment-377392981). 
Ideally, we'd want to bypass our EC2 and let the users upload/download directly through S3.
